11ый проект
Scoobe09/java-filmorate pull request #8
Opened 2024-02-23 18:04 UTC by Scoobe09

2024-02-24 15:12 UTC, dgumich requested changes

2024-02-24 15:12 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
Так никто не делает=) Поля все так же указывают private final, без ломбока. Но молодец, что изучаешь библиотеку.

2024-02-24 15:12 UTC, dgumich commented on src/main/resources/sql/test.sql
> +-- INSERT INTO FRIENDSHIPS(USER_ID, FRIEND_ID)
Тренировался? Молодец, это хорошо, но никакого закомментированного кода, в том числе и sql=)

2024-02-24 15:12 UTC, dgumich commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
Запросы написал, а где сама схема, молодец, а где сама схема бд? То есть должна быть картинка со всеми таблицами/строками/связями.

2024-02-24 15:12 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
>              throw new InvalidIdException("Пользователи уже друзья", HttpStatus.BAD_REQUEST);
А как же кейсы, что пользователей просто не существует? Надо добавит проверку, что под данными id есть пользователи.

2024-02-24 15:12 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        String sqlQuery = "INSERT INTO likes(film_id, user_id)" +
Мы никак не проверяем существует ли фильм/пользователь перед тем как выполнить запрос.

2024-02-24 17:49 UTC, Scoobe09 commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
поместил private final на поля

2024-02-24 17:50 UTC, Scoobe09 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        List<Film> str = jdbcTemplate.query(sqlQuery, (resultSet, rowNum) -> {
Исправил на filmsFromDb

2024-02-24 17:50 UTC, Scoobe09 commented on src/main/resources/sql/test.sql
> +-- INSERT INTO FRIENDSHIPS(USER_ID, FRIEND_ID)
Убрал весь код

2024-02-24 17:50 UTC, Scoobe09 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
Схема в файле README

2024-02-25 22:58 UTC, dgumich approved these changes

2024-02-25 22:58 UTC, dgumich commented on src/test/java/ru/yandex/practicum/filmorate/dao/UserDbStorageTest.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
В тестах такое тоже не используй

2024-02-28 17:16 UTC, merged